### ISSUE TITLE
Line 55 in examples/denoising.py

### ISSUE THREAD

**Issue by unanan** [stefanloock/pyshearlab#7]
I guess it may lose indentation from Line 54 to Line 56.
Or I'm wrong....

**Comment by adler-j** [comment]
I guess you mean this line:https://github.com/stefanloock/pyshearlab/blob/54f7958d572cdc6ba6837e8661665b4f3cbb2152/examples/denoising.py#L56

 (You should always link to the line and commit when referencing a line, since they tend to change).

Anyway, it is not a misstake, since `j` is assigned on the line above. With that said, it's bad style so I made a commit that should make this much more clear!
